"""Generate the CARD_META block in index.html from the nova-island-cards skill data.

CARD_META gives the AI theme generator (and anything else that wants it) one
compact record per card ID -- type, cost, class, health, ability tags, and a
plain-text description -- for every card the tool knows about, *including
Superpowers*, which CARD_DATA lacks entirely.

Source of truth is the Novadex snapshot bundled with the nova-island-cards
skill (https://github.com/thirteen-games/nova-island-cards). Cards are joined
by display name. Anything Novadex doesn't know (e.g. a brand-new card) falls
back to CARD_DATA's description with the HTML stripped.

Usage:
    python scripts/build_card_meta.py            # auto-locate cardData.json
    python scripts/build_card_meta.py --data PATH/TO/cardData.json

Re-run after a balance patch (refresh the skill's data first).
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HTML_PATH = os.path.join(HERE, '..', 'index.html')

BEGIN = '// BEGIN CARD_META (generated by scripts/build_card_meta.py -- do not edit by hand)'
END = '// END CARD_META'

CANDIDATE_DATA_PATHS = [
    os.path.expanduser('~/.claude/skills/nova-island-cards/data/cardData.json'),
    os.path.join(HERE, '..', '..', 'nova-island-cards', 'data', 'cardData.json'),
]

TYPE_NAMES = {1: 'Friend', 2: 'Power', 3: 'Superpower'}


def locate_data(explicit):
    paths = [explicit] if explicit else CANDIDATE_DATA_PATHS
    for p in paths:
        if p and os.path.isfile(p):
            return p
    sys.exit('cardData.json not found. Tried:\n  ' + '\n  '.join(paths)
             + '\nClone https://github.com/thirteen-games/nova-island-cards or pass --data.')


def parse_card_array(html, name):
    m = re.search(r'const %s = \[(.*?)\];' % name, html, re.S)
    if not m:
        sys.exit(f'could not find const {name} in index.html')
    rows = re.findall(r'\{id:(\d+),name:"([^"]*)",displayName:"([^"]*)",type:(\d)\}', m.group(1))
    return [dict(id=int(i), name=n, displayName=d, type=int(t)) for i, n, d, t in rows]


def parse_card_data(html):
    m = re.search(r'const CARD_DATA = (\{.*?\});\n', html, re.S)
    return json.loads(m.group(1)) if m else {}


def strip_html(s):
    return re.sub(r'\s+', ' ', re.sub(r'<[^>]*>', ' ', s or '')).strip()


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--data', help='path to Novadex cardData.json')
    ap.add_argument('--html', default=HTML_PATH, help='index.html to rewrite')
    args = ap.parse_args()

    data_path = locate_data(args.data)
    with open(data_path, encoding='utf-8') as f:
        novadex = json.load(f)
    # One entry per historical version; the live version has no `end`.
    current = {c['name'].lower(): c for c in novadex if 'end' not in c}

    with open(args.html, encoding='utf-8') as f:
        html = f.read()

    cards = (parse_card_array(html, 'FRIEND_CARDS')
             + parse_card_array(html, 'POWER_CARDS')
             + parse_card_array(html, 'SUPERPOWER_CARDS'))
    card_data = parse_card_data(html)

    meta = {}
    unmatched = []
    for c in cards:
        nx = current.get(c['displayName'].lower())
        cd = card_data.get(str(c['id']), {})
        if nx:
            tags = [t.strip() for t in (nx.get('tags') or '').split(',') if t.strip()]
            rec = dict(type=c['type'], cost=nx['cost'], cls=nx['class'], hp=nx.get('health', 0),
                       tags=tags, desc=strip_html(nx.get('description', '')))
        elif cd:
            unmatched.append(c['displayName'])
            rec = dict(type=c['type'], cost=cd.get('cost'), cls=cd.get('cls'), hp=cd.get('hp', 0),
                       tags=[], desc=strip_html(cd.get('desc', '')))
        else:
            unmatched.append(c['displayName'] + ' (no data at all)')
            rec = dict(type=c['type'], cost=None, cls=None, hp=0, tags=[], desc='')
        meta[c['id']] = rec

    # Novadex type 3/4 are both Superpowers; the tool only has type 3.
    body = json.dumps({str(k): meta[k] for k in sorted(meta)}, ensure_ascii=False, separators=(',', ':'))
    block = (f'{BEGIN}\n'
             f'// {len(meta)} cards from {os.path.basename(data_path)}; keys: type(1=Friend,2=Power,3=Superpower), cost, cls, hp, tags, desc\n'
             f'const CARD_META = {body};\n'
             f'{END}')

    if BEGIN in html and END in html:
        pre, rest = html.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        html = pre + block + post
        action = 'replaced'
    else:
        anchor = 'window._cardAbilities = CARD_ABILITIES;\n'
        if anchor not in html:
            sys.exit('anchor line not found; cannot insert CARD_META')
        html = html.replace(anchor, anchor + '\n' + block + '\n', 1)
        action = 'inserted'

    with open(args.html, 'w', encoding='utf-8', newline='\n') as f:
        f.write(html)

    by_type = {}
    for r in meta.values():
        by_type[TYPE_NAMES.get(r['type'], r['type'])] = by_type.get(TYPE_NAMES.get(r['type'], r['type']), 0) + 1
    print(f'{action} CARD_META: {len(meta)} cards {by_type} ({len(body):,} chars) from {data_path}')
    if unmatched:
        print('fell back to CARD_DATA for (not in Novadex):', ', '.join(unmatched))
    missing_sp = [c['displayName'] for c in cards if c['type'] == 3 and c['displayName'] in unmatched]
    if missing_sp:
        sys.exit('ERROR: superpowers without Novadex data: ' + ', '.join(missing_sp))


if __name__ == '__main__':
    main()
